sudo: false
language: rust
rust:
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
after_success:
- travis-cargo doc-upload
dd:
  secure: b/+wyuuswwV0PHW7XVgmAzn1mjae0fmxvuOvyW1Z2mE3hv9CBzdX6KrSaxAGKaaMpQFwsXNpz4v7ibP5It/4DfTkw63xRSSGwIoXfmXVm7eQVgC9Y+X620wnDub3lQPPDQCHswvxRN+pzp7OfnU0igowkgC9R6npX8fr88h9ilWz+LxoXUnH2ZH/x7icjB7K0HUYrtSkd3Zsh5to8KgeYkcJ68zZ+7WwFe9Uafhxit5Vx6mS2fFsr9GTxy+COV6own3JPAZsLiwCMX1JFG/q5INL7TbfI7sFKCjIhn3M/uR1yerg0/DQntL3LpTAF26qVHCq1o0r+oXafbhknOA/PXSJdyWJQmWvhgvzxUSOeD46MAKDe2hJg7cFPI4QOGq8rMNnwiKyivWEHOS97S57syHDofK1ZMZP8sTqZlsi1a7zDE9yFDtTGzlYrKf5BIfSzVbfpl9QK7GlNIkLyxgErieAA7u9Xe8FTLi9yO6m64kKPK4nOAmQl7u5ifIQzSgnqpgXlO7qDI16tUdkskSqE8jemi9ZmNTv6zkeL3RrXicsXQk5JhcCJ38yyOLrYEDFE4w3hEMLq/RS7SmPbAMdZnGJqf0vTjRDHiNYdRVSMZkbO/dEkKkcENj6IphKfDU3QuJ+wcq672FHKiBc4DILvcwMBqmm33JJuqMMZXCrDK8=
