sudo: false
language: rust
rust:
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
after_success:
- travis-cargo doc-upload
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: QtrIEgN6eLlA5vR9HMjtq1/lSqugBci3whK30XwZa4iw8QkLZi2kerXUww5Y+kh3eAeUCQsuvUjIAK4kPNAbcGJeoI15ECnHUG8hwZT/r6N3YYnNHmrC4sf6PnGsCadfmLLUIlZgvQPjL31iUZ2r16q6/w9swdCGz1W1HsD9n+9L+ngqH7UcShTcP3+i9T5ztsWBYeaDa6rzed2n/En1ZEsBrGfTKlJTSY+eENdrV4Tc+h0bOAXSKE1ssSAvMKTAqCHESN/zhGWuy1NbMzZyp/pAcqsmuL+u+E3+bJyDIcIlE0ievshEB+8fHlGHj4OpPCLISq7dOCPR9fMikTd3HoeTDRKm6SS0IzFOAcLK6DR8+MemL+icECTVghhC3+Rvx0s1kIZpZit4QjuisK3h/a56E4XRntepyWuRyZAPPS9dL4jnynX8QuG1MDNqu0jRq5HNI27kSCU1OMtTKL/k9tGCrzHElSUUZEdAoSny6Yb3UBdiO3f+iCAooJVXoKIUDLJCeyWtrrs2N4HEF8/YhPCJ3anoAit3A0W0v4n5wTkVHO13BQF2LZMGtaJgBRmaJesiFt6oDCU4DjaZmp2yHxeLyfIOYoaGB7Fx8DgKFrpn3pIkNHJh4Oht5XkK2xJYYtTRpEQg40B66KhMbaupKp97uPqEC+tT2XfnDePMeik=
